apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: pfeihebacr.azurecr.io/user:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          env:
            - name: DATABASE_URL
              value: "mysql://root:root@mysql-service:3306/userdb?serverVersion=8.0"
      imagePullSecrets:
        - name: acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: LoadBalancer
